config/routes.rb
Olearum::Application.routes.draw do
  
  match "texto/articulo/:id" => "texto#articulo" 
  get "texto/inicio"

  resources :sesiones
  get 'login' => 'sesiones#new', :as => 'login'
  get 'logout' => 'sesiones#destroy', :as => 'logout'
  resources :email
      match "email"=> "email#new"

  resources :services
  resources :relaciones
  resources :relacions
  resources :nombre_relacions do
         get :relaciones, :on => :member

  end
  resources :generica_relacions
  resources :museo_relacions
  resources :pieza_relacions
  resources :museo_pieza_relacions
  resources :info_relacions
  resources :museo_info_relacions
  resources :hito_relacions
  resources :museo_hito_relacions
  resources :camino_relacions
  resources :museo_camino_relacions

  resources :museos do
     get :relacion, :on => :member
    resource :ficha
    resource :entorno do
        resources :hitos do
      get :relacion, :on => :member
    end
        resources :caminos do
           get :relacion, :on => :member
           resources :coordenadas
            end
        resources :urbanos
    end
    resources :espacios 
    resources :piezas do
      get :relacion, :on => :member
    end
    resources :eventos
    resources :premios
    resources :varios
      resources :medios

    resources :publicacions
    resources :infos do
      get :relacion, :on => :member
    end
    resources :servicios
  end
  
  resources :labels do
    resources :labels
  end

  resources :genericas do
         get :relacion, :on => :member

  end

  
  
  
  get "admin/index"
  get "admin/search"
  get "admin/seleccionar"

  get "olearum/index"
      match "admin"=> "inicio#index"
      match "no_compatible"=> "admin#no_compatible"
      match "no_screen"=> "admin#no_screen"

  get "resources/show"
  get "resources/detalla"
  get "resources/museostextfile"
  match "resources/hitostextfile/:id" => "resources#hitostextfile"
  match "resources/hitotextf/:id" => "resources#hitotextf"
  match "resources/hitotextfg/:id" => "resources#hitotextfg"
  match "resources/museostextfile/:id" => "resources#museostextfile"
    match "resumen/museo/:id"=> "resumen#museo"
     match "resumen/articulos"=> "resumen#articulos"

    match "resources/medio/:id"=> "resources#medio"
    match "resources/camino/:url"=> "resources#camino"

  match 'mapa' => 'resources#show'

  get "resources/search"
  get "resources/fly"

   root :to => 'resources#show'

end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :label
  has_many :labels,:dependent=>:destroy
  has_and_belongs_to_many :genericas,:join_table=>'genericas_labels'
  has_and_belongs_to_many :fichas,:join_table=>'fichas_labels'
  has_and_belongs_to_many :piezas,:join_table=>'piezas_labels'
  has_and_belongs_to_many :espacios,:join_table=>'espacios_labels'
  has_and_belongs_to_many :eventos,:join_table=>'eventos_labels'

  has_and_belongs_to_many :publicacions,:join_table=>'publicacions_labels'

  ##### espacios: hitos, caminos, urbanos
  has_and_belongs_to_many :hitos,:join_table=>'hitos_labels'
  has_and_belongs_to_many :caminos,:join_table=>'caminos_labels'
  has_and_belongs_to_many :urbanos,:join_table=>'urbanos_labels'
 
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
    def index 
        if params[:label_id]
            @label=Label.find(params[:label_id])
            @labels=@label.labels
        else
          @labels=Label.all
        end    
    end
    
    def new
        @label=Label.new
    end
    def create
        @label=Label.create(params[:label])
        
        @label.save
        
        if !@label.label_id.nil?
            redirect_to label_path(@label.label_id)     
        else               
           redirect_to @label
        end        
        
    
    end
    def show
        @label=Label.find(params[:id])
    end
    def edit
        @label=Label.find(params[:id])
    end

    def update
        @label = Label.find(params[:id])

        respond_to do |format|
            if @label.update_attributes(params[:label])
                 format.html { redirect_to @label, :notice => 'Informacion actualizada'}
            else
                format.html { render :action => "edit"}
            end
        end
    end



    def destroy
        
       @label=Label.find(params[:id])
        if @label.label_id.nil? || params[:index]
            @label.destroy
            redirect_to labels_url
        else
            destino=@label.label_id  
            @label.label_id=nil
            @label.save
            redirect_to label_path(params[:label_id])
         end
   
  end
end

app/views/labels/_form.html.erb
<%=form_for @label do |f|%>
    <%=f.label :nombre,:class=>'label'%>
    <%=f.text_field :nombre%>
    <br/>
    <%=f.submit 'Guardar',:class=>'btn btn-success'%> o <%=link_to 'cancelar',labels_path%>
<%end%>

app/views/labels/_formhijas.html.erb
<%= form_for([@label, @label.labels.build]) do |h| %>

    <%= h.hidden_field :label_id,:value=>@label.id %>
    <%= h.label :nombre %>
    <%= h.text_field :nombre %>
  
  
  <div class="actions">
    <%= h.submit 'Guardar etiqueta hija',:class=>'btn' %>
  </div>

  <%end%>

app/views/labels/edit.html.erb
<h1>Editar etiqueta</h1>
<%=render 'form'%>

app/views/labels/index.html.erb
<h1> <%if !@label.nil?%>Etiquetas hijas de <%= @label.nombre%><%else%>Listado de etiquetas<%end%></h1>

<table class='table zebra-striped' id='ordenar'>
<thead>

<th>Nombre</th>
<th>Jerarquía</th>
<th>Etiquetas hijas</th>

<th>Acciones</th>
</thead>
<tbody>
<%@labels.each do |label|%>
    <tr>
    <td><%=label.nombre%></td>
     <td><%=genealogia(label)%></td>
    <td><%label.labels.each do |l|%><%=l.nombre%>&nbsp;<%end%></td>
    <td>
    <%= link_to 'Ver',label,:class=>'btn btn-success'%>
    <%= link_to 'Editar',edit_label_path(label),:class=>'btn btn-warning'%>
    <%= link_to 'Borrar',label_path(label,:index=>'true'),:method=>:delete,:confirm=>'¿Seguro que desea borrar la informacion? Las etiquetas hijas se eliminaran',:class=>'btn btn-danger'%>
    </td>
    </tr>
<%end%>
</tbody>
</table>
<%= link_to 'Añadir etiqueta principal',new_label_path,:class=>'btn'%>
<hr>
<i> * Para añadir una etiqueta a una existente haga click en "ver" la etiqueta existente</i>
<hr>

app/views/labels/new.html.erb
<h1>Nueva etiqueta principal</h1>
<%=render 'form'%>

app/views/labels/show.html.erb
<h1>Mostrando etiqueta</h1>
<label class='label'>Nombre</label>
<p><%=@label.nombre%></p>

<label class='label'>Etiquetas hijas</label>
<%@label.labels.each do |lab|%>
   <p><b><%=lab.nombre%></b> <%= link_to 'Borrar', [lab.label, lab], :confirm => 'Seguro?',    :method => :delete,:class=>'btn btn-mini btn-danger' %></p>
<%end%>

<%=render 'formhijas'%>
<br/>
<%=link_to 'Editar',edit_label_path(@generica),:class=>'btn'%> o <%=link_to 'Ir al listado',labels_path%>