config/routes.rb
Olearum::Application.routes.draw do
  
  match "texto/articulo/:id" => "texto#articulo" 
  get "texto/inicio"

  resources :sesiones
  get 'login' => 'sesiones#new', :as => 'login'
  get 'logout' => 'sesiones#destroy', :as => 'logout'
  resources :email
      match "email"=> "email#new"

  resources :services
  resources :relaciones
  resources :relacions
  resources :nombre_relacions do
         get :relaciones, :on => :member

  end
  resources :generica_relacions
  resources :museo_relacions
  resources :pieza_relacions
  resources :museo_pieza_relacions
  resources :info_relacions
  resources :museo_info_relacions
  resources :hito_relacions
  resources :museo_hito_relacions
  resources :camino_relacions
  resources :museo_camino_relacions

  resources :museos do
     get :relacion, :on => :member
    resource :ficha
    resource :entorno do
        resources :hitos do
      get :relacion, :on => :member
    end
        resources :caminos do
           get :relacion, :on => :member
           resources :coordenadas
            end
        resources :urbanos
    end
    resources :espacios 
    resources :piezas do
      get :relacion, :on => :member
    end
    resources :eventos
    resources :premios
    resources :varios
      resources :medios

    resources :publicacions
    resources :infos do
      get :relacion, :on => :member
    end
    resources :servicios
  end
  
  resources :labels do
    resources :labels
  end

  resources :genericas do
         get :relacion, :on => :member

  end

  
  
  
  get "admin/index"
  get "admin/search"
  get "admin/seleccionar"

  get "olearum/index"
      match "admin"=> "inicio#index"
      match "no_compatible"=> "admin#no_compatible"
      match "no_screen"=> "admin#no_screen"

  get "resources/show"
  get "resources/detalla"
  get "resources/museostextfile"
  match "resources/hitostextfile/:id" => "resources#hitostextfile"
  match "resources/hitotextf/:id" => "resources#hitotextf"
  match "resources/hitotextfg/:id" => "resources#hitotextfg"
  match "resources/museostextfile/:id" => "resources#museostextfile"
    match "resumen/museo/:id"=> "resumen#museo"
     match "resumen/articulos"=> "resumen#articulos"

    match "resources/medio/:id"=> "resources#medio"
    match "resources/camino/:url"=> "resources#camino"

  match 'mapa' => 'resources#show'

  get "resources/search"
  get "resources/fly"

   root :to => 'resources#show'

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
    mount_uploader :imagen,ImagenUploader
    belongs_to :museo
    has_and_belongs_to_many :labels
end

app/controllers/fichas_controller.rb
 class FichasController < ApplicationController
    def show
        @museo=Museo.find(params[:museo_id])
        if @museo.ficha.nil?
             @museo.ficha=Ficha.create  ####Ojo al 1-1 asi es muy limpio
             @museo.save
        end
        @ficha=@museo.ficha
            
    end 
    def edit
        @museo=Museo.find(params[:museo_id])
        @ficha=@museo.ficha
    end
    
    def update
        @museo = Museo.find(params[:museo_id])
        @ficha=@museo.ficha

            if @ficha.update_attributes(params[:ficha])
                  redirect_to museo_ficha_path(@museo), :notice => 'Informacion actualizada'
            end
    end

end

app/views/fichas/_form.html.erb
<br/>


<ul class="nav nav-tabs"  data-tabs="tabs">
  <li class="active" ><a href="#imagen" data-toggle="tab">Imagen</a></li>
  <li><a href="#descripcion"  data-toggle="tab">Descripción</a></li>
  <li><a href="#contacto"  data-toggle="tab">Contacto</a></li>
  <li><a href="#llegar"  data-toggle="tab">Como llegar</a></li>
  <li><a href="#horario"  data-toggle="tab">Horario</a></li>
  <!-- li><a href="#etiquetas"  data-toggle="tab">Etiquetas</a></li -->
  <li><a href="#coordenadas"  data-toggle="tab">Coordenadas</a></li>
</ul>
<%= cargaeditor%> <!--  Application helper a las text areas :class => "tinymce" -->

<%=form_for [@museo, @museo.ficha],:html=>{:multipart=>true} do |f|%>
    <div  id="tabs" class="tab-content" >
        <div class="tab-pane active" id="imagen">
        <%=f.label :imagen,:class=>'label'%>
        <%if @ficha.imagen_url.to_s!='' %>
            <%=imagentam(@ficha,'64x64')%>
            <%= f.check_box :remove_imagen %>
            Borrar imagen
        <%end%>
        <br/>
        <%= f.file_field :imagen %>
    </div>
    <div class="tab-pane" id="descripcion">
        <%=f.label :descripcion,:class=>'label'%>
        <%= f.text_area :descripcion,  :class => "tinymce", :rows => 10, :cols => 120 %>
    </div>
    <div class="tab-pane" id="contacto">
        <%=f.label :contacto,:class=>'label'%>
        <%= f.text_area :contacto,  :class => "tinymce" ,:rows=>5,:cols=>100%>    
    </div>
    <div class="tab-pane" id="llegar">
        <label class='label'>Como llegar</label>
        <%= f.text_area :llegar,  :class => "tinymce" ,:rows=>5,:cols=>100%>
    </div>
    <div class="tab-pane" id="horario">
        <%=f.label :horario,:class=>'label'%>
        <%= f.text_area :horario,:class => "tinymce" ,:rows=>5,:cols=>100%>
    </div>
     <!--div class="tab-pane" id="etiquetas">
     <%=etiquetar @ficha%>
    </div-->
	<div class="tab-pane" id="coordenadas">

	<%=render(:file => "/shared/coordenadas_edit",:locals => {:input_form=>"ficha", :modelo=>@ficha, :formulario=>f} )  %>
</div>
    
   
</div> 
    
    <br/>
    <%=f.submit 'Guardar',:class=>'btn btn-success'%> o <%=link_to 'cancelar',museo_ficha_path(@museo)%>
<%end%>
<script>
 $("#tabs").tabs();
</script>

app/views/fichas/edit.html.erb
<h1>Edición ficha técnica: <%=@museo.nombre%></h1>
<%=render 'form'%>

app/views/fichas/show.html.erb
<h1>Ficha técnica: <%=@ficha.museo.nombre%></h1>
<!-- %=etiquetas @ficha% -->
<label class='label'>Imagen</label>
<p><%=imagentam(@ficha,'64x64')%>&nbsp;</p>

<label class='label'>Descripcion</label>
<p><%=raw  @ficha.descripcion%></p>

<label class='label'>Contacto</label>
<p><%= raw @ficha.contacto%>&nbsp;</p>

<label class='label'>Como llegar</label>
<p><%=raw @ficha.llegar%>&nbsp;</p>

<label class='label'>Horarios</label>
<%= raw  @ficha.horario%>
	<%=render(:file => "/shared/coordenadas_show",:locals => { :modelo=>@ficha} )  %>





<br/>
<%=link_to 'Editar',edit_museo_ficha_path(@museo),:class=>'btn'%> o <%=link_to 'Volver al museo',@museo%>