config/routes.rb
Olearum::Application.routes.draw do
  
  match "texto/articulo/:id" => "texto#articulo" 
  get "texto/inicio"

  resources :sesiones
  get 'login' => 'sesiones#new', :as => 'login'
  get 'logout' => 'sesiones#destroy', :as => 'logout'
  resources :email
      match "email"=> "email#new"

  resources :services
  resources :relaciones
  resources :relacions
  resources :nombre_relacions do
         get :relaciones, :on => :member

  end
  resources :generica_relacions
  resources :museo_relacions
  resources :pieza_relacions
  resources :museo_pieza_relacions
  resources :info_relacions
  resources :museo_info_relacions
  resources :hito_relacions
  resources :museo_hito_relacions
  resources :camino_relacions
  resources :museo_camino_relacions

  resources :museos do
     get :relacion, :on => :member
    resource :ficha
    resource :entorno do
        resources :hitos do
      get :relacion, :on => :member
    end
        resources :caminos do
           get :relacion, :on => :member
           resources :coordenadas
            end
        resources :urbanos
    end
    resources :espacios 
    resources :piezas do
      get :relacion, :on => :member
    end
    resources :eventos
    resources :premios
    resources :varios
      resources :medios

    resources :publicacions
    resources :infos do
      get :relacion, :on => :member
    end
    resources :servicios
  end
  
  resources :labels do
    resources :labels
  end

  resources :genericas do
         get :relacion, :on => :member

  end

  
  
  
  get "admin/index"
  get "admin/search"
  get "admin/seleccionar"

  get "olearum/index"
      match "admin"=> "inicio#index"
      match "no_compatible"=> "admin#no_compatible"
      match "no_screen"=> "admin#no_screen"

  get "resources/show"
  get "resources/detalla"
  get "resources/museostextfile"
  match "resources/hitostextfile/:id" => "resources#hitostextfile"
  match "resources/hitotextf/:id" => "resources#hitotextf"
  match "resources/hitotextfg/:id" => "resources#hitotextfg"
  match "resources/museostextfile/:id" => "resources#museostextfile"
    match "resumen/museo/:id"=> "resumen#museo"
     match "resumen/articulos"=> "resumen#articulos"

    match "resources/medio/:id"=> "resources#medio"
    match "resources/camino/:url"=> "resources#camino"

  match 'mapa' => 'resources#show'

  get "resources/search"
  get "resources/fly"

   root :to => 'resources#show'

end

app/models/hito.rb
class Hito < ActiveRecord::Base
  mount_uploader :imagen,ImagenUploader
   mount_uploader :archivo,DocumentoUploader
 belongs_to :entorno
  belongs_to :museo
    belongs_to :service

  has_many :hito_genericas
  has_many :genericas, :through => :hito_genericas

  acts_as_heir_of :relacionable
 def imagen_servicio
    if self.service!=nil
        return self.service.imagen
    else
        return ""
    end
  end
def nombre_select
"#{self.class}: #{nombre}"

end

def nombre_relacionable
nombre
end
  def nombre_ask
    "#{nombre}"    
  end


end

app/controllers/hitos_controller.rb
class HitosController < ApplicationController
    before_filter :pide_login
    def index
       @museo=Museo.find(params[:museo_id])
       @hitos=@museo.hitos
    end
    
    def new
        @museo=Museo.find(params[:museo_id])
        @entorno=@museo.entorno
        @hito=@entorno.hitos.new
    end
    def create
        @museo=Museo.find(params[:museo_id])
        @entorno=@museo.entorno
            if params[:hito][:service_id].nil?
                    flash[:notice] = "tienes que seleccionar una imagen para este hito!" 
                    redirect_to request.referer
                    elsif
        @hito=@entorno.hitos.create(params[:hito])
       
        @hito.save
        redirect_to museo_entorno_hito_path(:museo_id=>@museo,:id=>@hito)
        end
        
    end
    def show
        @hito=Hito.find(params[:id])
    end
    def edit
        @hito=Hito.find(params[:id])
        @entorno=@hito.entorno
        @museo=@entorno.museo
    end
    def relacion
        @hito=Hito.find(params[:id])
        @entorno=@hito.entorno
        @museo=@entorno.museo
    end
    def destroy
        @hito = Hito.find(params[:id])
        @museo=@hito.museo
        @hito.destroy

        respond_to do |format|
            format.html { redirect_to museo_entorno_hitos_path(@museo) }
        end
    end
    def update
        @hito = Hito.find(params[:hito][:id])
        @entorno=@hito.entorno
        @museo=@entorno.museo
            if params[:hito][:service_id].nil?
                    flash[:notice] = "tienes que seleccionar una imagen para este hito!" 
                    redirect_to request.referer
              elsif @hito.update_attributes(params[:hito])
                  redirect_to museo_entorno_hito_path(:museo_id=>@museo,:id=>@hito), :notice => 'Informacion actualizada'
            end
    end
end

app/views/hitos/_form.html.erb
<%= cargaeditor%>
<%=form_for( [@museo,@entorno, @hito]) do |f|%>
    <%=f.hidden_field :id%>  

    <%=f.label :nombre,:class=>'label'%>
    <%=f.text_field :nombre%>  
<%=f.label "Articulos relacionados",:class=>'label'%>
<%= f.select :generica_ids, Generica.all.collect {|x| [x.titulo, x.id]}, {}, :multiple => true, :empty=>true %>


    <!-- Servicios vinculados service_id  -->
     <%=f.label :imagen,:class=>'label'%>
      <% Service.all.each do |ser| %>
        <%= image_tag(ser.imagen,:size=>'32x32') %>       
        <b><%=ser.descripcion %></b>       
        <%= f.radio_button :service_id, ser.id %>
       </span>
     <% end %>


    <%=f.label :descripcion,:class=>'label'%>
        <%= f.text_area :descripcion,  :class => "tinymce", :rows => 10, :cols => 120 %>
    
		<%=f.label "KML",:class=>'label'%>
	 <%= f.file_field :archivo %>
  <%if @hito.archivo_url.to_s!=''%>
 <br> <b> Archivo KML ya adjuntado</b><br>
   <%= link_to @hito.archivo, @hito.archivo_url.to_s %>
   <br>
          <%= f.check_box :remove_archivo %>
          <%= t('destroy')%>
  <%end%>
	

	
     <%=f.label :imagen,:class=>'label'%>
    <%if @hito.imagen_url.to_s!='' %>
        <%=imagentam(@hito,'64x64')%>
        <%= f.check_box :remove_imagen %>
        Borrar imagen
    <%end%>
    <br/>
    <%= f.file_field :imagen %> 
	<%=render(:file => "/shared/coordenadas_edit",:locals => {:input_form=>"hito", :modelo=>@hito, :formulario=>f} )  %>

    <br/>
    <%=f.submit 'Guardar',:class=>'btn btn-success'%> o <%=link_to 'cancelar',museo_entorno_hitos_path(@museo)%>
<%end%>

app/views/hitos/edit.html.erb
<h1>Edición de Hito: <%=@hito.nombre%> de <%=@hito.entorno.museo.nombre%></h1>

<%=render 'form'%>

app/views/hitos/index.html.erb
<h1>Hitos para el museo: <%=@museo.nombre%></h1>
<br/>
<table class='table zebra-striped'>
<tr>
<th>Nombre</th>
<th>Servicio</th>

<th>Descripcion</th>
<th>Imagen</th>
<th>Acciones</th>
</tr>
<%@hitos.each do |hito|%>
<tr>
<td><a href="/?resourceId=<%=hito.predecessor.id%>" target="_blank"><%=hito.predecessor.id%></a> - <%=hito.nombre%></td>
    <td><%=image_tag(hito.imagen_servicio,:size=>'64x64')%></td>

<td><%=raw hito.descripcion%></td>
<td><%=imagentam(hito,'64x64')%></td>
<td>
<%= link_to 'Ver',museo_entorno_hito_path(:museo_id=>@museo,:id=>hito),:class=>'btn btn-success'%>
<%= link_to 'Editar',edit_museo_entorno_hito_path(:museo_id=>@museo,:id=>hito),:class=>'btn btn-warning'%>
<%= link_to 'Relaciones',relacion_museo_entorno_hito_path(:museo_id=>@museo,:id=>hito),:class=>'btn btn-success'%>&nbsp;

<%= link_to 'Borrar',museo_entorno_hito_path(:museo_id=>@museo,:id=>hito),:method=>:delete,:confirm=>'¿Seguro que desea borrar la información?',:class=>'btn btn-danger'%>

</td>
</tr>
<%end%>
</table>
<%= link_to 'Añadir hito',new_museo_entorno_hito_path(@museo),:class=>'btn'%> o <%=link_to 'Volver al entorno',museo_entorno_path(@museo)%>

app/views/hitos/new.html.erb
<h1>Nuevo hito para el museo: <%=@museo.nombre%></h1>
<%=render 'form'%>

app/views/hitos/relacion.html.erb
<h1>Hito: <%=@hito.nombre%></h1>
<%=render(:file => "/shared/formrelaciones.html.erb",:locals => {:pathito=>"hito", :relacionable=>@hito} )  %>
<br/>
<%=link_to 'Volver a lista de hitos',museo_entorno_hitos_path(@museo)%>

app/views/hitos/show.html.erb
<h1>Hito: <%=@hito.nombre%> de <%=@hito.entorno.museo.nombre%></h1>
<br/>

<label class='label'>Imagen</label>
<p><%=imagentam(@hito,'64x64')%>&nbsp;</p>

<label class='label'>Nombre</label>
<p><%=@hito.nombre%>&nbsp;</p>
<label class='label'>Servicio</label>
<p><%=image_tag(@hito.imagen_servicio,:size=>'64x64')%> <%=@hito.service.descripcion%></p>

<label class='label'>Descripción de la hito</label>
<p><%=raw @hito.descripcion%>&nbsp;</p>
<label class='label'>KML</label>

<p> 
  <% if @hito.archivo_url.to_s != "" %>
  <%= link_to @hito.archivo, @hito.archivo_url.to_s %>
  <% end %>
 </p>

	<%=render(:file => "/shared/coordenadas_show",:locals => { :modelo=>@hito} )  %>


<label class='label'>Articulos Relacionados</label>
<p><%=@hito.genericas.map {|x| x.titulo}%>&nbsp;</p>


<br/>
<%=link_to 'Editar',edit_museo_entorno_hito_path(@museo, @entorno),:class=>'btn'%> o <%=link_to 'Volver a hitos',museo_entorno_hitos_path(@museo)%>