config/routes.rb
Olearum::Application.routes.draw do
  
  match "texto/articulo/:id" => "texto#articulo" 
  get "texto/inicio"

  resources :sesiones
  get 'login' => 'sesiones#new', :as => 'login'
  get 'logout' => 'sesiones#destroy', :as => 'logout'
  resources :email
      match "email"=> "email#new"

  resources :services
  resources :relaciones
  resources :relacions
  resources :nombre_relacions do
         get :relaciones, :on => :member

  end
  resources :generica_relacions
  resources :museo_relacions
  resources :pieza_relacions
  resources :museo_pieza_relacions
  resources :info_relacions
  resources :museo_info_relacions
  resources :hito_relacions
  resources :museo_hito_relacions
  resources :camino_relacions
  resources :museo_camino_relacions

  resources :museos do
     get :relacion, :on => :member
    resource :ficha
    resource :entorno do
        resources :hitos do
      get :relacion, :on => :member
    end
        resources :caminos do
           get :relacion, :on => :member
           resources :coordenadas
            end
        resources :urbanos
    end
    resources :espacios 
    resources :piezas do
      get :relacion, :on => :member
    end
    resources :eventos
    resources :premios
    resources :varios
      resources :medios

    resources :publicacions
    resources :infos do
      get :relacion, :on => :member
    end
    resources :servicios
  end
  
  resources :labels do
    resources :labels
  end

  resources :genericas do
         get :relacion, :on => :member

  end

  
  
  
  get "admin/index"
  get "admin/search"
  get "admin/seleccionar"

  get "olearum/index"
      match "admin"=> "inicio#index"
      match "no_compatible"=> "admin#no_compatible"
      match "no_screen"=> "admin#no_screen"

  get "resources/show"
  get "resources/detalla"
  get "resources/museostextfile"
  match "resources/hitostextfile/:id" => "resources#hitostextfile"
  match "resources/hitotextf/:id" => "resources#hitotextf"
  match "resources/hitotextfg/:id" => "resources#hitotextfg"
  match "resources/museostextfile/:id" => "resources#museostextfile"
    match "resumen/museo/:id"=> "resumen#museo"
     match "resumen/articulos"=> "resumen#articulos"

    match "resources/medio/:id"=> "resources#medio"
    match "resources/camino/:url"=> "resources#camino"

  match 'mapa' => 'resources#show'

  get "resources/search"
  get "resources/fly"

   root :to => 'resources#show'

end

app/models/info.rb
class Info < ActiveRecord::Base

  belongs_to :museo
  belongs_to :generica

  acts_as_heir_of :relacionable

    
  def nombre_select
    "#{self.class}: #{titular(self)}"    
  end

  def nombre_relacionable
    titular(self)    
  end
  
  def descripcion
    if !generica.blank?
          "#{generica.descripcion}"
        else
           return "Sin articulo asociado. Id: #{id}"
      end
    end
  
     def nombre_ask
        "#{titular(self)}"
    end
   def titular(info)
     if !info.generica.blank?
          "#{info.generica.titulo}"
        else
           return "Sin articulo asociado. Id: #{info.id}"
      end
    end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
    def index
        @museo=Museo.find(params[:museo_id])
        @infos=@museo.infos
    end
    def new
        @museo=Museo.find(params[:museo_id])
        @info=@museo.infos.new
    end
    def create
        @museo=Museo.find(params[:museo_id])
        @info=@museo.infos.create(params[:info])
        @info.save
        redirect_to museo_info_path(:museo_id=>@museo,:id=>@info)
    end
    def show
        @info=Info.find(params[:id])
    end
    def edit
         @info=Info.find(params[:id])
         @museo=@info.museo
    end
    def relacion
         @info=Info.find(params[:id])
         @museo=@info.museo
    end
    def destroy
        @info = Info.find(params[:id])
        @museo=@info.museo
        @info.destroy

        respond_to do |format|
            format.html { redirect_to museo_infos_path(@museo) }
        end
    end
    def update
        @info = Info.find(params[:id])
        @museo=@info.museo

            if @info.update_attributes(params[:info])
                  redirect_to museo_info_path(:museo_id=>@museo,:id=>@info), :notice => 'Informacion actualizada'
            end
    end
end

app/helpers/infos_helper.rb
module InfosHelper
  
  def dameTiposRI
    %w{panel video interactivo maqueta}
  end
  
    def titulo(info)
     if !info.generica.nil?
          "#{info.generica.titulo}"
        else
           return "Sin articulo asociado. Id: #{info.id}"
      end
    end
    def url(info)
        if !info.generica.nil?
            return link_to(info.generica.titulo,generica_path(info.generica))
       else 
            return ''
        end
    end
end

app/views/infos/_form.html.erb
<%=form_for [@museo,@info] do |f|%>

    <%=f.label :tipo,:class=>'label'%>
    <%= f.select(:tipo_ri, dameTiposRI()) %>

    <%=f.label :articulo,:class=>'label'%>
    <%=f.collection_select(:generica_id, Generica.all, :id,:titulo,:prompt => 'Elija la información')%>
    <br/>
    <%=f.submit 'Guardar',:class=>'btn btn-success'%> o 
	<%=link_to 'cancelar',museo_infos_path(@museo)%>
<%end%>

app/views/infos/edit.html.erb
<h1>Edición de recurso interpretativo </h1>
<%=render 'form'%>

app/views/infos/index.html.erb
<h1> Recursos interpretativos enlazados a: <%=@museo.nombre%></h1>
<table class='table zebra-striped'>
<tr>
<th>Título</th>
<th>Tipo</th>
<th>Enlace</th>
<th>Acciones</th>
</tr>
<%@infos.each do |info|%>
<tr>
<td><%=titulo(info)%></td>
<td><%=info.tipo_ri%></td>
<td><%=url(info)%></td>

<td>
<%= link_to 'Ver',museo_info_path(:museo_id=>info.museo,:id=>info),:class=>'btn btn-success'%>
<%= link_to 'Relaciones',relacion_museo_info_path(:museo_id=>info.museo,:id=>info),:class=>'btn btn-success'%>&nbsp;

<%= link_to 'Editar',edit_museo_info_path(:museo_id=>info.museo,:id=>info),:class=>'btn btn-warning'%>
<%= link_to 'Borrar',museo_info_path(:museo_id=>info.museo,:id=>info),:method=>:delete,:confirm=>'¿Seguro que desea borrar esta info?',:class=>'btn btn-danger'%>

</td>
</tr>
<%end%>
</table>
<%= link_to 'Enlazar resurso interpretativo',new_museo_info_path(@museo),:class=>'btn'%> o <%=link_to 'Volver al museo,',museo_path(@museo)%>

app/views/infos/new.html.erb
<h1>Nuevo enlace a recurso interpretativo:</h1>
<h3> <%=@museo.nombre%></h3>
<%=render 'form'%>

app/views/infos/relacion.html.erb
<h1>Recurso interpretativo: <%=titulo(@info)%></h1>
<%=render(:file => "/shared/formrelaciones.html.erb",:locals => {:pathito=>"info", :relacionable=>@info} )  %>
<br/>
<%=link_to 'Volver a lista de recursos interpretativos',museo_info_path(@info)%>

app/views/infos/show.html.erb
<h1>Enlace a recurso interpretativo: </h1>
<h3><%=@info.museo.nombre%></h3>


<label class='label'>Título</label>
<p><%=titulo(@info)%> &nbsp;</p>
<label class='label'>Tipo</label>
<p><%=@info.tipo_ri%>&nbsp;</p>

<label class='label'>Enlace al contenido</label>
<p><%=url(@info)%>&nbsp;</p>

<br/>
<%=link_to 'Editar',edit_museo_info_path(@museo),:class=>'btn'%> o 

<%=link_to 'Volver a recursos interpretativos del museo ',museo_infos_path(@museo)%>